# Generated by Django 3.1.7 on 2021-02-26 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('interface', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_data', models.JSONField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='god.servicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='god.servicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableInterfacesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaces', models.JSONField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='god.servicemodel')),
            ],
        ),
    ]
