# Generated by Django 3.1.7 on 2021-02-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('data', models.JSONField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='god.statusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceModel',
            fields=[
                ('interface', models.CharField(max_length=100)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='god.statusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('log_data', models.JSONField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='god.statusmodel')),
            ],
        ),
    ]
