# Generated by Django 3.1.7 on 2021-02-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='id',
            new_name='service_id',
        ),
        migrations.RenameField(
            model_name='interfacemodel',
            old_name='id',
            new_name='service_id',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='id',
            new_name='service_id',
        ),
    ]
